### ISSUE TITLE
CI Failures - GitHub Releases

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/shabby-pages#10]
Currently the [GitHub Action](https://github.com/sparkfish/shabby-pages/blob/dev/.github/workflows/main.yml) for this repository is set to run daily, building a 50-image set of Shabby Pages and releasing this as a [GitHub Release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

This is [failing](https://github.com/sparkfish/shabby-pages/runs/6176552849?check_suite_focus=true#step:4:5), because releasing this way requires tagging a commit, which we don't currently do. It's also not clear if we would need to commit to the repo every day, generating a new tag each time, and release against that, or if we could release against the same commit tag and still get a versioned history of files. Probably the former.

**Comment by jboarman** [comment]
Thanks @shotor.  Your PR seems to have done the trick!

To recap, @shotor created a new workflow to run on a cron schedule that tags the lastest on `dev` with the current date.  That tagging action then triggers the daily build workflow which creates a new release of 50 random shabby image patches.
