### ISSUE TITLE
Where to download the dataset?

### ISSUE THREAD

**Issue by saifullah3396** [sparkfish/shabby-pages#70]
Hi, 

Great work! Where can I download the train/test sets that were already generated in the paper?

**Comment by jboarman** [comment]
Hi @saifullah3396, we’re still in pre-print status on this paper and the associated dataset, but we are hoping to be ready to release during the summer.

Can you share more about your interests or how you plan to use the project?

**Comment by saifullah3396** [comment]
Hey @jboarman thanks for your response! 

I mainly plan to use it for large-scale pertaining of generative denoising models for binarization or corruption removal.

**Comment by saifullah3396** [comment]
I am actually curious about the particular reason why you cannot share the dataset under preprint status? I am thinking if sharing the dataset privately under some sort of agreement would be alright for research purposes? I have actually been looking for large-scale datasets for tasks such as binarization / learning corruption styles with fixed train/test sets so that we don't have to resort to very small datasets like DIBCO, LDM, etc. The earlier the better!

**Comment by jboarman** [comment]
Thanks @saifullah3396.  You make a compelling argument.  We'll work to get this available as soon as possible.
