### ISSUE TITLE
Will the model work on document images in other languages like Chinese?

### ISSUE THREAD

**Issue by Yikai-Liao** [sparkfish/shabby-pages#82]
I just wonder about the generalization ability of the model.

Also, if there are some charts and iconographs in the input document images，would the model work well？

**Comment by Yikai-Liao** [comment]
it's my fault，it' just a dataset

**Comment by gxlarson** [comment]
The dataset was created using [Augraphy](https://github.com/sparkfish/augraphy). If you wanted to build off of the Shabby Pages datset (to add more samples with charts/iconographs) or create a new one specifically for charts and iconographs, you would just have to find images/documents with these and then use Augraphy to create a noisy version.
